### PR TITLE
Remove the SHUTDOWNABLE signature

### PR DESCRIPTION
**Pull request by djs55**
This was a misunderstanding over the semantics of `close` which have been [clarified upstream](https://github.com/mirage/mirage/commit/caf220efda27dfbf5d90ffcdc5db86e2a39528a0). Since it's a backwards-incompatible change we also bump the version to 2.0.0.

This PR shouldn't be merged until the users of this signature have been ported to the vanilla `V1_LWT.FLOW` signature:
- `mirage/ocaml-git`: uses `mirage-flow` but not `SHUTDOWNABLE`
- `docker/vpnkit`: https://github.com/docker/vpnkit/blob/ecdded8799428fc58aa1d35f34b8dbff8cc9baf6/src/hostnet/lib/sig.ml#L2
- `djs55/ocaml-hvsock`: https://github.com/djs55/ocaml-hvsock/blob/9da157786e9bb113f0f31f00be86ffaae0b585d0/lwt/flow_lwt_hvsock_shutdown.mli#L24

### CODE REVIEW

**Comment by yomimono** [comment]
It's been rather quiet, so I'll mention that I'm in favor of this change but need to do some work on vpnkit to support it.

**Comment by hannesm** [comment]
wondering what the status hereof is?  I'm always in favour of removing code, esp. if it is confusing.

**Comment by yomimono** [comment]
^ @djs55 , since I no longer do any work on vpnkit and honestly have no memory of what the state of this is 😅

**Comment by hannesm** [comment]
ping, @djs55 any chance you can rebase this PR?

**Comment by hannesm** [comment]
integrated into #48

**Pull request closed without merging**
